// Generated by delombok at Fri Sep 16 17:50:31 CEST 2022
package de.amthor.gendb.payload;

public class LoginDto {
    private String usernameOrEmail;
    private String password;

    @java.lang.SuppressWarnings("all")
    public LoginDto() {
    }

    @java.lang.SuppressWarnings("all")
    public String getUsernameOrEmail() {
        return this.usernameOrEmail;
    }

    @java.lang.SuppressWarnings("all")
    public String getPassword() {
        return this.password;
    }

    @java.lang.SuppressWarnings("all")
    public void setUsernameOrEmail(final String usernameOrEmail) {
        this.usernameOrEmail = usernameOrEmail;
    }

    @java.lang.SuppressWarnings("all")
    public void setPassword(final String password) {
        this.password = password;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof LoginDto)) return false;
        final LoginDto other = (LoginDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$usernameOrEmail = this.getUsernameOrEmail();
        final java.lang.Object other$usernameOrEmail = other.getUsernameOrEmail();
        if (this$usernameOrEmail == null ? other$usernameOrEmail != null : !this$usernameOrEmail.equals(other$usernameOrEmail)) return false;
        final java.lang.Object this$password = this.getPassword();
        final java.lang.Object other$password = other.getPassword();
        if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof LoginDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $usernameOrEmail = this.getUsernameOrEmail();
        result = result * PRIME + ($usernameOrEmail == null ? 43 : $usernameOrEmail.hashCode());
        final java.lang.Object $password = this.getPassword();
        result = result * PRIME + ($password == null ? 43 : $password.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LoginDto(usernameOrEmail=" + this.getUsernameOrEmail() + ", password=" + this.getPassword() + ")";
    }
}
