// Generated by delombok at Fri Sep 16 17:50:31 CEST 2022
package de.amthor.gendb.payload;

import java.util.List;

public class PostResponse {
    private List<PostDto> content;
    private int pageNo;
    private int pageSize;
    private long totalElements;
    private int totalPages;
    private boolean last;

    @java.lang.SuppressWarnings("all")
    public List<PostDto> getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public int getPageNo() {
        return this.pageNo;
    }

    @java.lang.SuppressWarnings("all")
    public int getPageSize() {
        return this.pageSize;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalElements() {
        return this.totalElements;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalPages() {
        return this.totalPages;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isLast() {
        return this.last;
    }

    @java.lang.SuppressWarnings("all")
    public void setContent(final List<PostDto> content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    public void setPageNo(final int pageNo) {
        this.pageNo = pageNo;
    }

    @java.lang.SuppressWarnings("all")
    public void setPageSize(final int pageSize) {
        this.pageSize = pageSize;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalElements(final long totalElements) {
        this.totalElements = totalElements;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalPages(final int totalPages) {
        this.totalPages = totalPages;
    }

    @java.lang.SuppressWarnings("all")
    public void setLast(final boolean last) {
        this.last = last;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PostResponse)) return false;
        final PostResponse other = (PostResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getPageNo() != other.getPageNo()) return false;
        if (this.getPageSize() != other.getPageSize()) return false;
        if (this.getTotalElements() != other.getTotalElements()) return false;
        if (this.getTotalPages() != other.getTotalPages()) return false;
        if (this.isLast() != other.isLast()) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PostResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getPageNo();
        result = result * PRIME + this.getPageSize();
        final long $totalElements = this.getTotalElements();
        result = result * PRIME + (int) ($totalElements >>> 32 ^ $totalElements);
        result = result * PRIME + this.getTotalPages();
        result = result * PRIME + (this.isLast() ? 79 : 97);
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PostResponse(content=" + this.getContent() + ", pageNo=" + this.getPageNo() + ", pageSize=" + this.getPageSize() + ", totalElements=" + this.getTotalElements() + ", totalPages=" + this.getTotalPages() + ", last=" + this.isLast() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PostResponse(final List<PostDto> content, final int pageNo, final int pageSize, final long totalElements, final int totalPages, final boolean last) {
        this.content = content;
        this.pageNo = pageNo;
        this.pageSize = pageSize;
        this.totalElements = totalElements;
        this.totalPages = totalPages;
        this.last = last;
    }

    @java.lang.SuppressWarnings("all")
    public PostResponse() {
    }
}
